server:
  port: ${PORT:8080}

#  servlet:
#    context-path: /app
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp:
        use_jdbc_metadata_defaults: false
      id:
        new_generator_mappings: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password
#
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:password}



    flyway:
    baseline-on-migrate: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG
